2023 data updates
carbonplan/compliance-users pull request #121
Opened 2024-01-05 04:47 UTC by freyac

This an update with the new compliance data released in December 2023. 

There are two loose ends I need to track down by emailing CARB: 
1. There's a facility id (104091) that appears in compliance data but not facility data. 
2. There's a project idea that I think is a typo (CAFR-6339-A).

2024-01-05 23:32 UTC, badgley approved these changes

2024-01-08 15:01 UTC, katamartin requested changes
See details in comment below, but I think updating the data used in the tool will require more testing on the frontend (for example, we still need to add 2022 to the [reporting periods filter](https://github.com/carbonplan/compliance-users/blob/f26abf19aad04860f12fdb914dae5454e19f3629/components/use-store.js#L15-L19)).

2024-01-08 15:01 UTC, katamartin commented on docs/make-updates.md
> +## Steps for annual data updates
✨ 🎉

2024-01-08 16:48 UTC, freyac commented on components/use-store.js
> +  'https://raw.githubusercontent.com/carbonplan/compliance-users/main/data/outputs/user_data_v3.0.json'
implementing option 1!

2024-01-08 17:01 UTC, katamartin reviewed
Looking much better! Possible to add `2022` to the list of options here?
https://github.com/carbonplan/compliance-users/blob/f26abf19aad04860f12fdb914dae5454e19f3629/components/use-store.js#L15-L19

2024-01-08 19:55 UTC, katamartin approved these changes
Once we update to use the real URL, I say we merge this 🚢

2024-01-08 19:55 UTC, katamartin commented on components/use-store.js
> +//   'https://raw.githubusercontent.com/carbonplan/compliance-users/main/data/outputs/user_data_v3.0.json'
Let's restore this and merge!

2024-01-08 20:01 UTC, merged